export const LOAD_USER = "LOAD_USER";
export const LOAD_USER_SUCCES = "LOAD_USER_SUCCES";
export const LOAD_USER_AUTHORIZE = "LOAD_USER_AUTHORIZE";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";
export const RESET_USER = "RESET_USER";
